server:
  port: 8087
  servlet:
    context-path: '/ead-authuser'

spring:
  application:
    name: authuser
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
      username: configserver
      password: ead123
  datasource:
    password: ${PSQL_PASS}
    username: ${PSQL_USER}
    url: jdbc:postgresql://${PSQL_HOST}:5432/ead-authuser-v2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # not needed in hibernate 6+
        show_sql: true
        format_sql: true
  rabbitmq:
    port: 5672
    host: host.docker.internal

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace # shows preparedStatement parameters
    com:
      lsalmeida.authuser:
        config: info

authuser:
  refreshscope:
    name: John Doe

management:
  endpoints:
    web:
      exposure:
        include: 
          - refresh
          - health

api:
  client:
    base-url: course
    endpoint: ${API_COURSE_ENDPOINT}
  broker:
    exchange:
      userEvent: ead.userevent # exchange name

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: time_based
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        maxAttempts: 3
        waitDuration: 5s

